const { IconNames } = require('@blueprintjs/icons')
exports.usedIcons = [
	IconNames.EYE_OPEN,
	IconNames.DISABLE,
	IconNames.PLAY,
	IconNames.TICK_CIRCLE,
	IconNames.KEY,
	IconNames.LOCK,
	IconNames.CARET_DOWN,
	IconNames.CARET_RIGHT,
	IconNames.ERROR,
	IconNames.FLASH,
	IconNames.MOON,
	IconNames.GLOBE_NETWORK,
	IconNames.CLOUD_UPLOAD,
	IconNames.CODE,
	IconNames.ARCHIVE,
	IconNames.CHEVRON_BACKWARD,
	IconNames.CHEVRON_FORWARD,
	IconNames.CHEVRON_LEFT,
	IconNames.CHEVRON_RIGHT,
	IconNames.WARNING_SIGN,
	IconNames.REMOVE,
	IconNames.DELETE,
	IconNames.INFO_SIGN,
]
